INSERT INTO Livre
VALUES
(1, "Une étude en rouge", "Arthur Conan Doyles"),
(2, "Le chien des Baskervilles", "Arthur Conan Doyles"),
(3, "Le signes des quatre", "Arthur Conan Doyles"),
(4, "La valée de ", "Arthur Conan Doyles"),
(5, "Mort sur le nil", "Agatha Christie"),
(6, "Le crime de l'orient express", "Agatha Christie"),
(7, "Les vacances d'Hercules Poirot", "Agatha Christie"),
(8, "Rendez-avec la mort", "Agatha Christie"),
(9, "Un cadavre dans la bibliothèque", "Agatha Christie"),
(10, "ABC contre Poirot", "Agatha Christie"),
(11, "Poirot quitte la scène", "Agatha Christie"),
(12, "Meutre en Mésopotamie", "Agatha Christie"),
(13, "L'affaire Protheroe", "Agatha Christie"),
(14, "Le club de Mardi", "Agatha Christie"),
(15, "Mr Brown", "Agatha Christie"),
(16, "Rendez-avec la mort", "Agatha Christie"),
(17, "La Mystérieuse Affaire de Styles", "Agatha Christie"),
(18, "Le Crime du golf", "Agatha Christie"),
(19, "Les Enquêtes d'Hercule Poirot", "Agatha Christie"),
(20, "L'Homme au complet marron", "Agatha Christie"),
(21, "Le Secret de Chimneys", "Agatha Christie"),
(22, "Le Meurtre de Roger Ackroyd", "Agatha Christie"),
(23, "Les Quatre	roman	Hercule Poirot", "Agatha Christie"),
(24, "Le Train bleu", "Agatha Christie"),
(25, "Les Sept Cadrans", "Agatha Christie"),
(26, "Mystérieux Mr Quinn", "Agatha Christie"),
(27, "La Maison du péril", "Agatha Christie"),
(28, "Le crime est notre affaire", "Agatha Christie"),
(29, "Cinq Heures vingt-cinq", "Agatha Christie"),
(30, "Miss Marple au Club du Mardi", "Agatha Christie"),
(31, "Le seigneur des anneaux : la communauté de l'anneau", "J.R.R Tolkien"),
(32, "Le seigneur des anneaux : les deux tours", "J.R.R Tolkien"),
(33, "Le seigneur des anneaux : le retour du roi", "J.R.R Tolkien"),
(34, "Le Silmarillion", "J.R.R Tolkien"),
(35, "Bilbo le hobbit", "J.R.R Tolkien"),
(36, "Les aventures de Tom Bombadil", "J.R.R Tolkien"),
(37, "Contes et légendes inachevées : le premier âge", "J.R.R Tolkien"),
(38, "Contes et légendes inachevées : le second âge", "J.R.R Tolkien"),
(39, "Contes et légendes inachevées : le troisième âge", "J.R.R Tolkien");